apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - quota.yaml

namespace: cch-recette

images:
  - name: ghcr.io/olivinfo/quotes
    newTag: develop
  - name: ghcr.io/olivinfo/users
    newTag: develop
  - name: ghcr.io/olivinfo/search
    newTag: develop

patches:
  - path: patch-ingress.yaml
