apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes
spec:
  replicas: 1
  selector:
    matchLabels:
      service: quotes
  template:
    metadata:
      labels:
        service: quotes
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: quotes-service
        image: ghcr.io/olivinfo/quotes:latest
        env:
        - name: REDIS_HOST
          value: "redis-svc"
        - name: REDIS_PORT
          value: "6379"
        - name: ADMIN_KEY
          valueFrom:
            secretKeyRef:
              name: quotes-secrets
              key: ADMIN_KEY
        ports:
        - containerPort: 5000