apiVersion: v1
kind: ResourceQuota
metadata:
  name: app-quota
spec:
  hard:
    requests.cpu: "800m"      
    requests.memory: "800Mi"
    limits.cpu: "1500m"       
    limits.memory: "1500Mi"
    pods: "8"