apiVersion: v1
kind: Service
metadata:
  name: users-svc
spec:
  type: ClusterIP
  selector:
    service: users
  ports:
    - name: web
      port: 80
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: quotes-svc
spec:
  type: ClusterIP
  selector:
    service: quotes
  ports:
    - name: web
      port: 80
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: search-svc
spec:
  type: ClusterIP
  selector:
    service: search
  ports:
    - name: web
      port: 80
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  type: ClusterIP
  selector:
    service: redis
  ports:
    - name: tcp
      port: 6379
      targetPort: 6379